# Generated by Django 5.0.2 on 2024-03-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='musics',
        ),
        migrations.AddField(
            model_name='album',
            name='musics',
            field=models.ManyToManyField(to='music.music'),
        ),
    ]
