# Generated by Django 5.0.2 on 2024-03-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('about', models.TextField(blank=True)),
                ('released_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
