# Generated by Django 5.0.2 on 2024-03-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=128)),
                ('date_of_birth', models.DateField(auto_now_add=True, verbose_name='Date of birth')),
                ('albums', models.CharField(max_length=256)),
                ('songs', models.CharField(max_length=256)),
                ('information', models.TextField(blank=True)),
            ],
        ),
    ]
