# Generated by Django 5.0.2 on 2024-03-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='albums',
        ),
        migrations.AddField(
            model_name='artist',
            name='albums',
            field=models.ManyToManyField(to='album.album'),
        ),
    ]
